### ISSUE TITLE
rails サーバを起動できるようにしたい

### ISSUE THREAD

**Issue by u9r52sld** [u9r52sld/wikibot#7]
# 受入基準
- [x] rails s でサーバが起動できる

# その他
1. ```Puma caught this error: Missing `secret_key_base` for 'development' environment, set this value in `config/secrets.yml` (RuntimeError)  ```
config/secrets.yml を下記内容で作成
  ```
development:
  secret_key_base: <rake secrets で出力される値>
test:
  secret_key_base: <rake secrets で出力される値>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
```
2. ```Cannot load `Rails.application.database_configuration`: Could not load database configuration. No such file - ["config/database.yml"]```  
設定回りの修正. DBを使わない設定にした。
本来であれば db を使用しないアプリを作成する場合は `rails new myApp -O` コマンドで rails アプリを作成する
http://stackoverflow.com/questions/821251/how-to-configure-ruby-on-rails-with-no-database
